import React from "react";
import Card from "../../components/Card";
import Compo from "../../components/Compo.tsx";
import Category from "../../components/Category.tsx";
import search from "../../assets/images/search_orange.svg";
import { SearchBar } from "../../style/SearchBar";
import styled, { keyframes } from "styled-components";
import ModalPortal from "../../components/modal/ModalPortal";
import Modal from "../../components/modal/Modal";
import useCustomModal from "../../hooks/useCustomModal";


export default function Home() {
  const arr = [1, 2, 3, 4, 5];
  const { modalOpen, setModalOpen, showModal } = useCustomModal();

  return (
    <>
      <Wrap>
        <SearchBar1>
          <input
            type="text"
            name=""
            id=""
            placeholder="검색어를 입력해주세요."
          />
          <img src={search} alt="" />
        </SearchBar1>
        <Category></Category>
        <Event></Event>
        <Compo></Compo>
        <Div>
          <>
            {arr.map((arr) => (
              <Card />
            ))}
          </>
        </Div>

        <Compo></Compo>
        <Div>
          <>
            {arr.map((arr) => (
              <Card />
            ))}
          </>
        </Div>

        <Compo></Compo>
        <Div>
          <>
            {arr.map((arr) => (
              <Card />
            ))}
          </>
        </Div>
      </Wrap>

      <ModalPortal>
        {modalOpen && (
          <Modal
            type="profile"
            modalOpen={modalOpen}
            setModalOpen={setModalOpen}
            // handleHeaderBtn={showModal}
            // handleModal={handleProfileDetail}
          />
        )}
      </ModalPortal>
    </>
  );
}

/* ----------------------------------------------
 * Generated by Animista on 2023-8-1 10:34:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */

const scale = keyframes` 
    0% {
      -webkit-transform: translateY(0);
              transform: translateY(0);
    
            }
    100% {
      -webkit-transform: translateY(-80px);
              transform: translateY(-80px);
    width:30%;
    margin-bottom: -50px;
    }
  `;

export const Wrap = styled.div`
  padding: 100px 17%;
  /* border-top: 0.5px solid rgba(0, 0, 0, 0.1); */
  @media (max-width: 768px) {
    padding: 26px 10%;
  }
`;
export const Div = styled.div`
  display: flex;
  /* width:100vw; */
  margin: 0 auto 20px;

  overflow-x: scroll;
  @media (max-width: 768px) {
    padding: 26px 10%;
    margin: 0 -40px 40px;
    padding: 10px 40px;
  }
`;
export const Event = styled.div`
  height: 228px;
  background: #f5f5f5;
  margin: 100px 0 21px;
`;
export const SearchBar1 = styled(SearchBar)`
  position: fixed;
  margin-left: 250px;

  animation: ${scale} 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  margin-bottom: 50px;
`;
